### ISSUE TITLE
'x' button doesn't update position when expanding the text boxes with typing.

### ISSUE THREAD

**Issue by acwilton** [Millersville-LittleBobbyTables/UML_Editor#4]
When you start to type into a class box, if it starts to expand then the x button in the top right corner doesn't move at all until you start to drag the box.

Seen here:
![image](https://user-images.githubusercontent.com/28691264/32146097-f8bb7de8-bca8-11e7-9fa8-ccd450da819e.png)

**Comment by zrzuch** [comment]
I fixed this issue, and I pushed the updates to testing and Zach branches.
