### ISSUE TITLE
Holding mouse on the corner of a button causes it to spazz out.

### ISSUE THREAD

**Issue by acwilton** [Millersville-LittleBobbyTables/UML_Editor#5]
When you hold your mouse at the corner of a button (that wasn't the last button to be pushed) it rapidly jumps back and forth between being regular sized and the shrunk down size that indicates you are hovering over the button.

**Comment by zrzuch** [comment]
This issue doesn't show in my version. What buttons? What do you mean by "regular sized and the shrunk down size"? You may need to clone to a new directory and then compile a jar file with:

javac Main.java
jar cfe SimpleUML.jar Main Main.class uml_elements/Arrow.class uml_elements/ArrowSelector.class uml_elements/UMLLayout.class 768px-Red_X.svg.png

**Comment by acwilton** [comment]
Can't recreate issue. Will reopen if it happens again and can be recreated.
